### ISSUE TITLE
Return proper user-agent version?

### ISSUE THREAD

**Issue by dermoth** [jamiesonbecker/owa-user-agent#3]
Hi,

I'm running this extension off local disk as I need to use a custom url. While testing the code I didn't like much how the header was modified, and especially that it would not sync up to the actual chrome version and could possibly cause compatibility issues, or trigger security alerts/blocks for outdated versions. For many years now the enhanced version has been disabled for Non-Windows chrome only regardless of the version, so all that needs to change it the OS portion of the user-agent, nothing else.

Would you please consider the following code to replace the user-agent?

```
function(details) {
    var headers = details.requestHeaders;
    for (var i = 0; i < headers.length; ++i) {
        if (headers[i].name === 'User-Agent') {
            headers[i].value = headers[i].value.replace(/(Mozilla\/\d+\.\d+ )\([^\)]+\)/, "\$1(Windows NT 6.1; WOW64)");
            break;
        }
    }
    return {requestHeaders: headers};
},
```

---

A note on the custom url... in my case the owa server url is behind a "proxy service" so there's path components before the `"hostname:port/owa/*"`, and I need to match `"*://*/*owa/*"` - i.e. anything with _owa/_ in the url would match which is probably not a good idea as a default!

A configuration for the url pattern would be nice, but then we'd probably need to match the url using a regex rather than simple chrome pattern matches. Either way I won't be writing a UI for that for lack of time.

Regards,

**Comment by jamiesonbecker** [comment]
This seems like a good idea.. I no longer have a personal requirement for this plugin since I (fortunately) don't have to deal with OWA anymore, but pull requests are happily accepted ;)

**Comment by jamiesonbecker** [comment]
I made this change (see https://github.com/jamiesonbecker/owa-user-agent/commit/1e30b7cfd9fe66320501671a20eec8675aa95b7c ) but I have no way of testing it :)

As far as custom URL, I'm open to ideas! Please open a new issue if you want it done differently.

Also, this project is looking for a new maintainer, but I'll keep doing this as long as people realize that I have no idea if it actually works or not ;)

**Comment by dermoth** [comment]
Thanks. I no longer have ways to test it myself anymore. I think a configuration option for the regex url match could be great, but I have nearly no experience developing extensions and no use for this one anymore so it's unlikely I will even try to do it.

It's pathetic Microsoft cannot fix their own code and we have to resort to an extension as this to use OWA (and this has been going on for almost a decade)... Your work on this extension was very much appreciated! :)

Regards

**Comment by jamiesonbecker** [comment]
It is indeed pathetic that Microsot still believes that the way to get everyone back onto windows is to do stupid tricks like this one. Thank you for your kind words and I'm glad you don't have to deal with this anymore either :) Take care!
