### ISSUE TITLE
Case sensitive?

### ISSUE THREAD

**Issue by bergkoet** [jamiesonbecker/owa-user-agent#4]
My organization uses a URL with 'OWA' in all caps instead of 'owa'.  Should the filter be able to catch that?

**Comment by jamiesonbecker** [comment]
Unfortunately, Chrome apparently doesn't support that ( https://stackoverflow.com/questions/16993372/chrome-extension-case-insensitive-content-script-matches ). I am no longer (fortunately!) in a position that requires me to access an OWA server, so if someone wants to take over as maintainer, please let me know.

I just modified the extension to also look for OWA, though, and you can install it as a developer extension if you need it!

**Comment by jamiesonbecker** [comment]
Extension updates should be published in next few minutes!

**Comment by bergkoet** [comment]
It works for me now, thanks!

**Comment by jamiesonbecker** [comment]
Excellent - thanks for testing & letting me know!!
